### ISSUE TITLE
Using TensorFlow backend

### ISSUE THREAD

**Issue by Giszy** [keras-team/keras-core#556]
Using TensorFlow backend
Epoch 1/3
Traceback (most recent call last):
  File "E:\custom_train_step_in_tensorflow.py", line 131, in <module>
    model.fit(x, y, epochs=3)
  File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python_310\lib\site-packages\tensorflow\python\eager\execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "E:\custom_train_step_in_tensorflow.py", line 131, in <module>
      model.fit(x, y, epochs=3)
    File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 118, in error_handler
      return fn(*args, **kwargs)
    File "C:\Python_310\lib\site-packages\keras_core\src\backend\tensorflow\trainer.py", line 307, in fit
      logs = self.train_function(iterator)
    File "C:\Python_310\lib\site-packages\keras_core\src\backend\tensorflow\trainer.py", line 112, in one_step_on_iterator
      outputs = self.distribute_strategy.run(
Node: 'StatefulPartitionedCall'
Could not find compiler for platform DML: NOT_FOUND: could not find registered compiler for platform DML -- was support for that platform linked in?
         [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_iterator_697]

The original code is at https://github.com/keras-team/keras-io/blob/master/guides/keras_core/custom_train_step_in_torch.py.

**Comment by fchollet** [comment]
> Could not find compiler for platform DML: NOT_FOUND: could not find registered compiler for platform DML -- was support for that platform linked in?

This error typically means that your TF runtime is not working. You can try to run any piece of TF code (in graph mode) to check.

**Comment by Giszy** [comment]
> > Could not find compiler for platform DML: NOT_FOUND: could not find registered compiler for platform DML -- was support for that platform linked in?
> 
> This error typically means that your TF runtime is not working. You can try to run any piece of TF code (in graph mode) to check.

The problem is self.jit_compile = jit_compile on line 71 in keras-core\keras_core\trainers\trainer.py. Because the computing device of tensorflow-directml-plugin has been set to 'GPU', but the general strategy adopted by keras requires self.jit_compile =True, which makes the computing device of xla seem to be unable to find. The logic of the code here should be modified to self.jit_compile = False. The suggested code is:
'''python
         if jit_compile and backend.backend() == "tensorflow":
             from keras_core.utils.module_utils import tensorflow as tf
        
             if tf.config.list_physical_devices("GPU"):
                 self.jit_compile = False
             else:
                 self.jit_compile = jit_compile
         else:
             self.jit_compile = jit_compile
'''

**Comment by fchollet** [comment]
Thanks for the suggestion. It makes sense that you couldn't use XLA with DirectML.

But `list_physical_devices` doesn't seem like a reliable way to detect DirectML, no? It will be non-empty if there's any GPU on your machine.

**Comment by Giszy** [comment]
> Thanks for the suggestion. It makes sense that you couldn't use XLA with DirectML.
> 
> But `list_physical_devices` doesn't seem like a reliable way to detect DirectML, no? It will be non-empty if there's any GPU on your machine.

- Thank you for your reply. I mostly use it on Windows, but TensorFlow (>1.11.0) recently ended CUDA support. For acceleration, I used TensorFlow based on DirectML-Plugin. When running keras-core, there is a problem that the XLA device cannot be found. Unfortunately, I can't give the code to detect the presence of DirectML, all I can do is describe the line of code where the problem might be.
