### ISSUE TITLE
Using TensorFlow backend (tensorflow-2.10.1-cp310-cp310-win_amd64.whl)

### ISSUE THREAD

**Issue by Giszy** [keras-team/keras-core#559]
Using TensorFlow backend
Epoch 1/3
Traceback (most recent call last):
  File "E:\custom_train_step_in_tensorflow.py", line 131, in <module>
    model.fit(x, y, epochs=3)
  File "C:\Python_310\lib\site-packages\keras_core\src\utils\traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\custom_train_step_in_tensorflow.py", line 102, in train_step
    gradients = tape.gradient(loss, trainable_vars)
AttributeError: 'str' object has no attribute 'base_dtype'

The original code is at https://github.com/keras-team/keras-io/blob/master/guides/keras_core/custom_train_step_in_tensorflow.py.

**Comment by fchollet** [comment]
Runs fine for me with TF 2.12 and 2.13. Perhaps you just need to upgrade to a more recent TF version. 2.10 was released 1 year ago.
