### ISSUE TITLE
Issue when installing `keras-core`

### ISSUE THREAD

**Issue by dranaivo** [keras-team/keras-core#639]
When trying to install the `keras-core`, following the instruction (after installing the `requirements.txt`) : 

> Run installation command from the root directory.
> `python pip_build.py --install`

I get this error : 
```
Traceback (most recent call last):
  File "/nfs/home/e608759/workspace_me/keras-core/tmp_build_dir/keras_core/src/utils/module_utils.py", line 24, in initialize
    self.module = importlib.import_module(self.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pip_build.py", line 60, in build
    namex.generate_api_files(package, code_directory="src", verbose=True)
  File "/nfs/home/e608759/workspace_me/keras-core/.venv_dev/lib/python3.8/site-packages/namex/generate.py", line 76, in generate_api_files
    if not hasattr(symbol, "_api_export_path"):
  File "/nfs/home/e608759/workspace_me/keras-core/tmp_build_dir/keras_core/src/utils/module_utils.py", line 33, in __getattr__
    self.initialize()
  File "/nfs/home/e608759/workspace_me/keras-core/tmp_build_dir/keras_core/src/utils/module_utils.py", line 26, in initialize
    raise ImportError(
ImportError: This requires the tensorflow_io module. You can install it via `pip install tensorflow_io
```

When `pip` installing `tensorflow_io`, the installation works fine. 

So I guess mentionning `tensorflow_io` in one of the requirements should work.

**Comment by fchollet** [comment]
Thanks for the report. This is fixed, you should now be able to run the installation script without installing tensorflow_io.
