### ISSUE TITLE
Load Model After Save It

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-core#684]
Hey, I'm trying to generate a model following the example detailed in https://keras.io/keras_core/guides/custom_train_step_in_torch/. Once the model generation script (main.py) finishes, I try to load the model using the test_model.py script and it throws this error: 

`Using TensorFlow backend
2023-08-09 12:00:24.822874: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-09 12:00:24.889032: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-09 12:00:24.889466: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-09 12:00:25.874927: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/mnt/c/Users/emide/PycharmProjects/TestKeras/test_model.py", line 3, in <module>
    final_model = keras.models.load_model("final_model.keras")
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/saving_api.py", line 177, in load_model
    return saving_lib.load_model(
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/saving_lib.py", line 153, in load_model
    model = deserialize_keras_object(
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/serialization_lib.py", line 679, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/models/model.py", line 485, in from_config
    return cls._from_config(config, custom_objects=custom_objects)
AttributeError: type object 'CustomModel' has no attribute '_from_config'
`

I also tried adding the decorator  `@keras.saving.register_keras_serializable()` to the CustomModel, but with no luck.

The example is as it is on the web, no additional loss functions or metrics have been added.

File `main.py`:
```
import os

os.environ["KERAS_BACKEND"] = "torch"

import torch
import keras_core as keras
import numpy as np

from Model import CustomModel


inputs = keras.Input(shape=(32,))
outputs = keras.layers.Dense(1)(inputs)
model = CustomModel(inputs, outputs)
model.compile(optimizer="adam", loss="mse", metrics=["mae"])

x = np.random.random((1000, 32))
y = np.random.random((1000, 1))
model.fit(x, y, epochs=3)
model.save("final_model.keras")
```
File `model.py`:
```
import torch
import keras_core as keras

@keras.saving.register_keras_serializable()
class CustomModel(keras.Model):
    def train_step(self, data):

        x, y = data


        self.zero_grad()


        y_pred = self(x, training=True)  # Forward pass
        loss = self.compute_loss(y=y, y_pred=y_pred)


        loss.backward()

        trainable_weights = [v for v in self.trainable_weights]
        gradients = [v.value.grad for v in trainable_weights]


        with torch.no_grad():
            self.optimizer.apply(gradients, trainable_weights)

        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(y, y_pred)

        return {m.name: m.result() for m in self.metrics}


```

File `test_model.py`:

```
import keras_core as keras

final_model = keras.models.load_model("final_model.keras")
final_model.summary()
```

I also tried to add the method `get_config` but without success. I use only CPU mode because my laptop doesn't have GPU.

My project structure:
![imagen](https://github.com/keras-team/keras-core/assets/140513018/e80651c9-616c-4c7c-95ca-2d51b1b2cbcf)

Thank you so much in advanced!

**Comment by sampathweb** [comment]
I created a Colab gist from your code and it loads back correctly - https://gist.github.com/sampathweb/295ea4c8b7fa964e8f58728f27e293ac

Since there's logic specific to Torch backend in your `train_step`, you may need to load back in `torch` backend.

**Comment by sampathweb** [comment]
Closing the issue for now.  Please re-open if it doesn't resolve your issue.
