### ISSUE TITLE
Load Model After Save It

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-core#689]
Hello @sampathweb , it works fine if it is loaded in the same run that generates the model. Try loading it in another colab, i.e. save the model, upload it to colab and try loading it from scratch. 

Closed issue: https://github.com/keras-team/keras-core/issues/684#issuecomment-1671932221

 Thanks for your time

**Comment by emi-research-dl** [comment]
I have tested storing simple models (not inheriting from the Model class, built with Sequential) and it stores and loads perfectly. It seems to be a Keras serialization/deserialization error (maybe because it doesn't correctly locate the CustomModel definition). The problem always comes when you store a model that inherits from the Model class and you try to load the model from scratch by executing a different script (even if this script contains the definition of the class that extends Model). 

First run: 
```
import os
os.environ["KERAS_BACKEND"]="torch"  # must be set before importing keras
import keras_core as keras
import torch
import numpy as np

@keras.saving.register_keras_serializable()
class CustomModel(keras.Model):
    def train_step(self, data):

        x, y = data


        self.zero_grad()

    
        y_pred = self(x, training=True)  # Forward pass
        loss = self.compute_loss(y=y, y_pred=y_pred)

  
        loss.backward()

        trainable_weights = [v for v in self.trainable_weights]
        gradients = [v.value.grad for v in trainable_weights]


        with torch.no_grad():
            self.optimizer.apply(gradients, trainable_weights)

        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(y, y_pred)

        return {m.name: m.result() for m in self.metrics}


inputs = keras.Input(shape=(32,))
outputs = keras.layers.Dense(1)(inputs)
model = CustomModel(inputs, outputs)
model.compile(optimizer="adam", loss="mse", metrics=["mae"])

# Just use `fit` as usual
x = np.random.random((1000, 32))
y = np.random.random((1000, 1))
model.fit(x, y, epochs=3)

model.save("final_model.keras")

# model = keras.models.load_model("final_model.keras")
# model.summary()
```

Second run:

```
import os
os.environ["KERAS_BACKEND"]="torch"  # must be set before importing keras
import keras_core as keras
import torch
import numpy as np

@keras.saving.register_keras_serializable()
class CustomModel(keras.Model):
    def train_step(self, data):

        x, y = data


        self.zero_grad()


        y_pred = self(x, training=True)  # Forward pass
        loss = self.compute_loss(y=y, y_pred=y_pred)


        loss.backward()

        trainable_weights = [v for v in self.trainable_weights]
        gradients = [v.value.grad for v in trainable_weights]


        with torch.no_grad():
            self.optimizer.apply(gradients, trainable_weights)

        for metric in self.metrics:
            if metric.name == "loss":
                metric.update_state(loss)
            else:
                metric.update_state(y, y_pred)

        return {m.name: m.result() for m in self.metrics}


# inputs = keras.Input(shape=(32,))
# outputs = keras.layers.Dense(1)(inputs)
# model = CustomModel(inputs, outputs)
# model.compile(optimizer="adam", loss="mse", metrics=["mae"])
# 
# # Just use `fit` as usual
# x = np.random.random((1000, 32))
# y = np.random.random((1000, 1))
# model.fit(x, y, epochs=3)
# 
# model.save("final_model.keras")

model = keras.models.load_model("final_model.keras")
model.summary()
```

Error after second run:
```
Using PyTorch backend.
Traceback (most recent call last):
  File "/mnt/c/Users/emide/PycharmProjects/TestKeras/main.py", line 57, in <module>
    model = keras.models.load_model("final_model.keras")
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/saving_api.py", line 177, in load_model
    return saving_lib.load_model(
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/saving_lib.py", line 153, in load_model
    model = deserialize_keras_object(
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/saving/serialization_lib.py", line 679, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/home/emi/miniconda3/envs/work/lib/python3.9/site-packages/keras_core/src/models/model.py", line 485, in from_config
    return cls._from_config(config, custom_objects=custom_objects)
AttributeError: type object 'CustomModel' has no attribute '_from_config'
```

**Comment by fchollet** [comment]
Thanks for the report. This looks like a bug. Looking into it.

**Comment by fchollet** [comment]
This issue should now be fixed at HEAD. Please check. You can pull the code from GitHub and run python pip_build.py --install to build and install the latest version of the package.

**Comment by emi-research-dl** [comment]
Thank you so much!! It works now perfectly!!
