### ISSUE TITLE
TraceArrayConversionError when using JAX as backend

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-core#718]
Hi, I am trying to process a simple training step using JAX as backend. When performing the calculation of the precision metric, Keras jax throws the following error: 
```
Traceback (most recent call last):
  File "/mnt/c/Users/emide/PycharmProjects/KerasCoreTemplates/main.py", line 65, in <module>
    model.fit(train_ds, epochs=3)
  File "/home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/c/Users/emide/PycharmProjects/KerasCoreTemplates/Jax/jax_trainer.py", line 69, in train_step
    this_metric_vars = metric.stateless_update_state(
  File "/home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1813, in tile
    result = broadcast_to(reshape(A, [j for i in A_shape for j in [1, i]]),
  File "/home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1191, in broadcast_to
    return util._broadcast_to(array, shape)
  File "/home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 388, in _broadcast_to
    if not isinstance(shape, tuple) and np.ndim(shape) == 0:
  File "<__array_function__ internals>", line 200, in ndim
  File "/home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3187, in ndim
    return asarray(a).ndim
jax.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on traced array with shape int32[].
The error occurred while tracing the function compiled_train_step at /home/emi/miniconda3/envs/dlenv/lib/python3.9/site-packages/keras_core/src/backend/jax/trainer.py:199 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:i32[1] = convert_element_type[new_dtype=int32 weak_type=False] b
    from line /mnt/c/Users/emide/PycharmProjects/KerasCoreTemplates/Jax/jax_trainer.py:69 (train_step)

  operation a:i32[] = convert_element_type[new_dtype=int32 weak_type=False] b
    from line /mnt/c/Users/emide/PycharmProjects/KerasCoreTemplates/Jax/jax_trainer.py:69 (train_step)
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError
```

It seems that numpy arrays inside Keras are not being properly casted.

My implementation: 

```
import keras_core as keras
import jax

@keras.saving.register_keras_serializable()
class JaxTrainer(keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.loss_tracker = keras.metrics.Mean(name="loss")
        self.precision = keras.metrics.Precision(name="precision")

    def compute_loss_and_updates(
        self,
        trainable_variables,
        non_trainable_variables,
        x,
        y,
        training=False,
    ):
        y_pred, non_trainable_variables = self.stateless_call(
            trainable_variables,
            non_trainable_variables,
            x,
            training=training,
        )
        loss = self.compute_loss(x, y, y_pred)
        return loss, (y_pred, non_trainable_variables)

    def train_step(self, state, data):
        (
            trainable_variables,
            non_trainable_variables,
            optimizer_variables,
            metrics_variables,
        ) = state
        x, y = data


        grad_fn = jax.value_and_grad(self.compute_loss_and_updates, has_aux=True)


        (loss, (y_pred, non_trainable_variables)), grads = grad_fn(
            trainable_variables,
            non_trainable_variables,
            x,
            y,
            training=True,
        )

        probs = keras.activations.softmax(y_pred)  # Compute the probabilities for the calc of metrics


        (
            trainable_variables,
            optimizer_variables,
        ) = self.optimizer.stateless_apply(
            optimizer_variables, grads, trainable_variables
        )

    
        new_metrics_vars = []
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars


        state = (
            trainable_variables,
            non_trainable_variables,
            optimizer_variables,
            new_metrics_vars,
        )
        return logs, state

    def test_step(self, state, data):

        x, y = data
        (
            trainable_variables,
            non_trainable_variables,
            metrics_variables,
        ) = state


        y_pred, non_trainable_variables = self.stateless_call(
            trainable_variables,
            non_trainable_variables,
            x,
            training=False,
        )

        probs = keras.activations.softmax(y_pred)  # Compute the probabilities for the calc of metrics
        loss = self.compute_loss(x, y, y_pred)

 
        new_metrics_vars = []
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars


        state = (
            trainable_variables,
            non_trainable_variables,
            new_metrics_vars,
        )
        return logs, state

    @property
    def metrics(self):
        return [self.loss_tracker, self.precision]
```

Thanks in advanced!

**Comment by emi-research-dl** [comment]
Using the built-in metrics within the `compile()` method, the same result is obtained.

```
import os

os.environ["KERAS_BACKEND"] = "jax"

import keras_core as keras
from keras_core import layers
from Tensorflow import TensorflowModel
from Torch import TorchModel
from Jax import JaxTrainer
from glob import glob
import tensorflow as tf

SEED = 42  # Set seed for reproducibility

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def mnist_process(x, y):
    x = tf.expand_dims(tf.cast(x, dtype=tf.float32), axis=-1)
    x = tf.divide(x, 255)
    y = tf.one_hot(y , depth=10)
    return x, y

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).\
                    map(mnist_process)
train_ds = train_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).\
                    map(mnist_process)
test_ds = test_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

if glob("*.keras"):

    loaded = keras.models.load_model("final_model.keras")
    loaded.evaluate(test_ds)
    loaded.summary()
else:
    # Create the Keras Model
    inputs = keras.Input(shape=(28, 28, 1))
    x = layers.Conv2D(filters=64, kernel_size=3, padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPool2D(pool_size=2, strides=2)(x)
    x = layers.Conv2D(filters=32, kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.Flatten()(x)
    outputs = layers.Dense(units=10, activation="softmax")(x)

    model = keras.Model(inputs=inputs, outputs=outputs)

    model.compile(optimizer="adam", loss=keras.losses.CategoricalCrossentropy(), metrics=["accuracy", keras.metrics.Recall(), keras.metrics.Precision()])
    model.summary()

    model.fit(train_ds, validation_data=test_ds, epochs=3)

    model.save("final_model.keras")



```

**Comment by fchollet** [comment]
Judging from the stack trace, JAX was hitting an issue with the `tile` op in the precision metric -- it needs to do a broadcast/reshape to a static shape, but it is basing it on a dynamic (traced) shape.

Basically, in `jnp.tile(x, repeats)`, `repeats` must be static.

I've fixed it by switching the logic to special-casing the static case before using `tile`.

**Comment by fchollet** [comment]
You can reinstall the package at HEAD for the fix.
