### ISSUE TITLE
JAX error after fix issue https://github.com/keras-team/keras-core/issues/718#top

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras-core#723]
Hello again! After the fix I get the following error:
```

Traceback (most recent call last):
  File "/mnt/c/Users/emide/PycharmProjects/KerasCoreTemplates/main.py", line 65, in <module>
    model.fit(train_ds, validation_data=test_ds, epochs=3)
  File "/home/emi/miniconda3/envs/venv/lib/python3.10/site-packages/keras_core/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/emi/miniconda3/envs/venv/lib/python3.10/site-packages/keras_core/src/trainers/trainer.py", line 733, in _pythonify_logs
    for key, value in sorted(logs.items()):
AttributeError: 'ArrayImpl' object has no attribute 'items'. Did you mean: 'item'?

```

_Originally posted by @emi-research-dl in https://github.com/keras-team/keras-core/issues/718#issuecomment-1678015694_

**Comment by emi-research-dl** [comment]
With this code, it runs perfectly:

```
import os

os.environ["KERAS_BACKEND"] = "jax"

import keras_core as keras
from keras_core import layers
from glob import glob
import tensorflow as tf

SEED = 42  # Set seed for reproducibility

# Construct and compile an instance of CustomModel
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def mnist_process(x, y):
    x = tf.expand_dims(tf.cast(x, dtype=tf.float32), axis=-1)
    x = tf.divide(x, 255)
    y = tf.one_hot(y , depth=10)
    return x, y

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).\
                    map(mnist_process)
train_ds = train_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).\
                    map(mnist_process)
test_ds = test_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

if glob("*.keras"):
    # New part
    loaded = keras.models.load_model("simply_model.keras")
    loaded.evaluate(test_ds)
    loaded.summary()
else:
    # Create the Keras Model
    inputs = keras.Input(shape=(28, 28, 1))
    x = layers.Conv2D(filters=64, kernel_size=3, padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPool2D(pool_size=2, strides=2)(x)
    x = layers.Conv2D(filters=32, kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.Flatten()(x)
    outputs = layers.Dense(units=10, activation="softmax")(x)
    model = keras.Model(inputs=inputs, outputs=outputs)

    callbacks = [
        keras.callbacks.ModelCheckpoint(
            filepath="simply_model.keras",
            save_best_only=True,
            monitor="val_loss",)
    ]

    model.compile(optimizer="adam", loss=keras.losses.CategoricalCrossentropy(), metrics=[keras.metrics.CategoricalAccuracy(),keras.metrics.Recall(),keras.metrics.Precision()])
    model.summary()

    model.fit(train_ds, validation_data=test_ds, epochs=3, verbose=1)

    model.save("simply_model.keras")


Using this two files not:

````jax_trainer.py```:

import keras_core as keras
import jax

@keras.saving.register_keras_serializable()
class JaxTrainer(keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.loss_tracker = keras.metrics.Mean(name="loss")
        self.precision = keras.metrics.Precision(name="precision")

    def compute_loss_and_updates(
        self,
        trainable_variables,
        non_trainable_variables,
        x,
        y,
        training=False,
    ):
        y_pred, non_trainable_variables = self.stateless_call(
            trainable_variables,
            non_trainable_variables,
            x,
            training=training,
        )
        loss = self.compute_loss(x, y, y_pred)
        return loss, (y_pred, non_trainable_variables)

    def train_step(self, state, data):
        (
            trainable_variables,
            non_trainable_variables,
            optimizer_variables,
            metrics_variables,
        ) = state
        x, y = data


        grad_fn = jax.value_and_grad(self.compute_loss_and_updates, has_aux=True)


        (loss, (y_pred, non_trainable_variables)), grads = grad_fn(
            trainable_variables,
            non_trainable_variables,
            x,
            y,
            training=True,
        )

        probs = keras.activations.softmax(y_pred)  # Compute the probabilities for the calc of metrics


        (
            trainable_variables,
            optimizer_variables,
        ) = self.optimizer.stateless_apply(
            optimizer_variables, grads, trainable_variables
        )

 
        new_metrics_vars = []
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars


        state = (
            trainable_variables,
            non_trainable_variables,
            optimizer_variables,
            new_metrics_vars,
        )
        return logs, state

    def test_step(self, state, data):

        x, y = data
        (
            trainable_variables,
            non_trainable_variables,
            metrics_variables,
        ) = state


        y_pred, non_trainable_variables = self.stateless_call(
            trainable_variables,
            non_trainable_variables,
            x,
            training=False,
        )

        probs = keras.activations.softmax(y_pred)  # Compute the probabilities for the calc of metrics
        loss = self.compute_loss(x, y, y_pred)


        new_metrics_vars = []
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars


        state = (
            trainable_variables,
            non_trainable_variables,
            new_metrics_vars,
        )
        return logs, state

    @property
    def metrics(self):
        return [self.loss_tracker, self.precision]
```

```main.py``` file for reproduce with "jax_trainer.py":

```
import os

os.environ["KERAS_BACKEND"] = "jax"

import keras_core as keras
from keras_core import layers
from Tensorflow import TensorflowModel
from Torch import TorchModel
from Jax import JaxTrainer
from glob import glob
import tensorflow as tf

SEED = 42  # Set seed for reproducibility


(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def mnist_process(x, y):
    x = tf.expand_dims(tf.cast(x, dtype=tf.float32), axis=-1)
    x = tf.divide(x, 255)
    y = tf.one_hot(y , depth=10)
    return x, y

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).\
                    map(mnist_process)
train_ds = train_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).\
                    map(mnist_process)
test_ds = test_ds.batch(64).\
                    shuffle(buffer_size=1024).\
                    prefetch(tf.data.AUTOTUNE)

if glob("*.keras"):

    loaded = keras.models.load_model("final_model.keras")
    loaded.evaluate(test_ds)
    loaded.summary()
else:

    inputs = keras.Input(shape=(28, 28, 1))
    x = layers.Conv2D(filters=64, kernel_size=3, padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPool2D(pool_size=2, strides=2)(x)
    x = layers.Conv2D(filters=32, kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.Flatten()(x)
    outputs = layers.Dense(units=10)(x)


    if os.environ["KERAS_BACKEND"] == "tensorflow":
        model = TensorflowModel(inputs=inputs, outputs=outputs)
    elif os.environ["KERAS_BACKEND"] == "torch":
        model = TorchModel(inputs=inputs, outputs=outputs)
    elif os.environ["KERAS_BACKEND"] == "jax":
        model = JaxTrainer(inputs=inputs, outputs=outputs)

    model.compile(optimizer="adam", loss=keras.losses.CategoricalCrossentropy(from_logits=True))
    model.summary()

    model.fit(train_ds, validation_data=test_ds, epochs=3)

    model.save("final_model.keras")
```

I think the problem might be related to my implementation of "jax_trainer.py" but I don't know. Using the files "main.py" and "jax_trainer.py" you can reproduce the situation.

Thanks in advanced!

**Comment by fchollet** [comment]
I haven't tried to run the code, but just looking at it I can tell that the issue is with your trainer code.

Specifically, paragraphs like this:

```python
        new_metrics_vars = []
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars
```

The return value of `logs` in `train_step`/`test_step` **must be a dict**. In your case it is a scalar tensor (the output of the last call to `metric.stateless_result()`, for the last metric).

So you should do something like:

```python
        new_metrics_vars = []
        logs = {}
        for metric in self.metrics:
            this_metric_vars = metrics_variables[
                               len(new_metrics_vars): len(new_metrics_vars) + len(metric.variables)
                               ]
            if metric.name == "loss":
                this_metric_vars = metric.stateless_update_state(this_metric_vars, loss)
            else:
                this_metric_vars = metric.stateless_update_state(
                    this_metric_vars, y, probs
                )
            logs[metric.name] = metric.stateless_result(this_metric_vars)
            new_metrics_vars += this_metric_vars
```

**Comment by emi-research-dl** [comment]
It was just caused by that, thank you very much!
